# Generated by Django 3.2 on 2023-03-21 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг цвета')),
            ],
        ),
        migrations.CreateModel(
            name='KindOfAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Вид животного')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг животного')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кличка')),
                ('old', models.IntegerField(verbose_name='Возраст питомца')),
                ('lifetime', models.IntegerField(verbose_name='Среднее время жизни')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.color', verbose_name='Цвет питомца')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.kindofanimal', verbose_name='Порода питомца')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хозяин питомца')),
            ],
        ),
    ]
