# Generated by Django 3.2 on 2023-03-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
