# Generated by Django 3.2 on 2023-03-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Фото питомца'),
        ),
    ]
