# Generated by Django 3.2 on 2023-03-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_animal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
